apiVersion: v1
kind: Service
metadata:
   name: nexus-service
   namespace: {{namespace}}
spec:
   type: LoadBalancer
   ports:
   -  port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
   -  port: 5000
      targetPort: 5000
      protocol: TCP
      name: docker
   selector:
      app: nexus
